<?php

namespace Tests\Unit\JavaScriptModules;

use App\Domain\Sections\Models\Section;
use App\JavaScriptModule;
use Tests\DbTestCase;

class JavaScriptModuleUnitTest extends DbTestCase
{
	
	protected function setUp(): void
	{
		$this->markTestSkipped();
		parent::setUp(); // TODO: Change the autogenerated stub
	}
	
	/** @test */
    public function it_can_compile_a_code_string()
    {
    	
    	$section = Factory(Section::class)->create();
    	
        $javascriptModule = JavaScriptModule::create([
            'name' => 'foo',
            'function_name' => 'openNav',
            'code' => '{{$var1}}',
            'parameters' => json_encode([
                [
                    'key' => 'var1',
                    'value' => 'testVar',
                    'type' => 'variable',
                ],
                [
                    'key' => 'var2',
	                'value' => 5,
                    'type' => 'section_fragment_id',
                ],
            ]),
        ]);
        
        $section->javaScriptModules()->attach($javascriptModule, [
        	'arguments' => json_encode([
		        [
			        'key' => 'var1',
			        'value' => 'testVar',
			        'type' => 'variable',
		        ],
		        [
			        'key' => 'var2',
			        'value' => 5,
			        'type' => 'section_fragment_id',
		        ],
	        ])
        ]);

        $this->assertEquals('openNav() { testVar }', $section->getJavaScriptCode());
    }
}
