<?php

namespace App\Domain\Sections\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

/**
 * App\Domain\Sections\Models\Avatar
 *
 * @property int $id
 * @property string $name
 * @property string $img_url
 * @property int $gender
 * @property int|null $job_title_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string $face_pad
 * @property int $face_index
 * @property-read \App\Domain\Sections\Models\JobTitle|null $jobTitle
 * @method static \Illuminate\Database\Eloquent\Builder|Avatar newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Avatar newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Avatar query()
 * @method static \Illuminate\Database\Eloquent\Builder|Avatar whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Avatar whereFaceIndex($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Avatar whereFacePad($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Avatar whereGender($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Avatar whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Avatar whereImgUrl($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Avatar whereJobTitleId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Avatar whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Avatar whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Avatar extends Model
{
    public function getGenderAttribute($value)
    {
        return $value == 0 ? 'male' : 'female';
    }

    public function jobTitle()
    {
        return $this->belongsTo(JobTitle::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Cache::forget('avatars');
    }
}
